// 80C390 processor definition file
// ================================


unit Sys_80C390;

interface

var
  P4        : byte absolute $80;
  DPL1      : byte absolute $84;
  DPH1      : byte absolute $85;
  DPS       : byte absolute $86;
  CKCON     : byte absolute $8E;
  EXIF      : byte absolute $91;
  P4CNT     : byte absolute $92;
  DPX       : byte absolute $93;
  DPX1      : byte absolute $95;
  C0RMS0    : byte absolute $96;
  C0RMS1    : byte absolute $97;
  SCON0     : byte absolute $98;
  SBUF0     : byte absolute $99;
  ESP       : byte absolute $9B;
  AP        : byte absolute $9C;
  ACON      : byte absolute $9D;
  C0TMA0    : byte absolute $9E;
  C0TMA1    : byte absolute $9F;
  P5        : byte absolute $A1;
  P5CNT     : byte absolute $A2;
  C0C       : byte absolute $A3;
  C0S       : byte absolute $A4;
  C0IR      : byte absolute $A5;
  C0TE      : byte absolute $A6;
  C0RE      : byte absolute $A7;
  SADDR0    : byte absolute $A9;
  SADDR1    : byte absolute $AA;
  C0M1C     : byte absolute $AB;
  C0M2C     : byte absolute $AC;
  C0M3C     : byte absolute $AD;
  C0M4C     : byte absolute $AE;
  C0M5C     : byte absolute $AF;
  C0M6C     : byte absolute $B3;
  C0M7C     : byte absolute $B4;
  C0M8C     : byte absolute $B5;
  C0M9C     : byte absolute $B6;
  C0M10C    : byte absolute $B7;
  SADEN0    : byte absolute $B9;
  SADEN1    : byte absolute $BA;
  C0M11C    : byte absolute $BB;
  C0M12C    : byte absolute $BC;
  C0M13C    : byte absolute $BD;
  C0M14C    : byte absolute $BE;
  C0M15C    : byte absolute $BF;
  SCON1     : byte absolute $C0;
  SBUF1     : byte absolute $C1;
  PMR       : byte absolute $C4;
  STATUS    : byte absolute $C5;
  MCON      : byte absolute $C6;
  TA        : byte absolute $C7;
  T2CON     : byte absolute $C8;
  T2MOD     : byte absolute $C9;
  RCAP2L    : byte absolute $CA;
  RCAP2H    : byte absolute $CB;
  TL2       : byte absolute $CC;
  TH2       : byte absolute $CD;
  COR       : byte absolute $CE;
  MCNT0     : byte absolute $D1;
  MCNT1     : byte absolute $D2;
  MA        : byte absolute $D3;
  MB        : byte absolute $D4;
  MC        : byte absolute $D5;
  C1RMS0    : byte absolute $D6;
  C1RMS1    : byte absolute $D7;
  WDCON     : byte absolute $D8;
  C1TMA0    : byte absolute $DE;
  C1TMA1    : byte absolute $DF;
  C1C       : byte absolute $E3;
  C1S       : byte absolute $E4;
  C1IR      : byte absolute $E5;
  C1TE      : byte absolute $E6;
  C1RE      : byte absolute $E7;
  EIE       : byte absolute $E8;
  MXAX      : byte absolute $EA;
  C1M1C     : byte absolute $EB;
  C1M2C     : byte absolute $EC;
  C1M3C     : byte absolute $ED;
  C1M4C     : byte absolute $EE;
  C1M5C     : byte absolute $EF;
  C1M6C     : byte absolute $F3;
  C1M7C     : byte absolute $F4;
  C1M8C     : byte absolute $F5;
  C1M9C     : byte absolute $F6;
  C1M10C    : byte absolute $F7;
  EIP       : byte absolute $F8;
  C1M11C    : byte absolute $FB;
  C1M12C    : byte absolute $FC;
  C1M13C    : byte absolute $FD;
  C1M14C    : byte absolute $FE;
  C1M15C    : byte absolute $FF;

  T2        : boolean absolute $90;
  T2EX      : boolean absolute $91;
  RXD1      : boolean absolute $92;
  TXD1      : boolean absolute $93;
  INT2      : boolean absolute $94;
  INT3      : boolean absolute $95;
  INT4      : boolean absolute $96;
  INT5      : boolean absolute $97;
  RI_0      : boolean absolute $98;
  TI_0      : boolean absolute $99;
  RB8_0     : boolean absolute $9A;
  TB8_0     : boolean absolute $9B;
  REN_0     : boolean absolute $9C;
  SM2_0     : boolean absolute $9D;
  SM1_0     : boolean absolute $9E;
  SM0FE_0   : boolean absolute $9F;
  ES0       : boolean absolute $AC;
  ET2       : boolean absolute $AD;
  ES1       : boolean absolute $AE;
  RXD0      : boolean absolute $B0;
  TXD0      : boolean absolute $B1;
  PS0       : boolean absolute $BC;
  PT2       : boolean absolute $BD;
  PS1       : boolean absolute $BE;
  RI_1      : boolean absolute $C0;
  TI_1      : boolean absolute $C1;
  RB8_1     : boolean absolute $C2;
  TB8_1     : boolean absolute $C3;
  REN_1     : boolean absolute $C4;
  SM2_1     : boolean absolute $C5;
  SM1_1     : boolean absolute $C6;
  SM0FE_1   : boolean absolute $C7;
  CPRL2     : boolean absolute $C8;
  CT2       : boolean absolute $C9;
  TR2       : boolean absolute $CA;
  EXEN2     : boolean absolute $CB;
  TCLK      : boolean absolute $CC;
  RCLK      : boolean absolute $CD;
  EXF2      : boolean absolute $CE;
  TF2       : boolean absolute $CF;
  F1        : boolean absolute $D1;
  RWT       : boolean absolute $D8;
  EWT       : boolean absolute $D9;
  WTRF      : boolean absolute $DA;
  WDIF      : boolean absolute $DB;
  PFI       : boolean absolute $DC;
  EPFI      : boolean absolute $DD;
  POR       : boolean absolute $DE;
  SMOD_1    : boolean absolute $DF;
  EX2       : boolean absolute $E8;
  EX3       : boolean absolute $E9;
  EX4       : boolean absolute $EA;
  EX5       : boolean absolute $EB;
  EWDI      : boolean absolute $EC;
  C1IE      : boolean absolute $ED;
  C0IE      : boolean absolute $EE;
  CANBIE    : boolean absolute $EF;
  PX2       : boolean absolute $F8;
  PX3       : boolean absolute $F9;
  PX4       : boolean absolute $FA;
  PX5       : boolean absolute $FB;
  PWDI      : boolean absolute $FC;
  C1IP      : boolean absolute $FD;
  C0IP      : boolean absolute $FE;
  CANBIP    : boolean absolute $FF;


const
  SINT0     = $23;
  TIMER2    = $2B;
  PWFAIL    = $33;
  SINT1     = $3B;
  EXTI2     = $43;
  EXTI3     = $4B;
  EXTI4     = $53;
  EXTI5     = $5B;
  WATCHD    = $63;
  CAN0      = $6B;
  CAN1      = $73;
  CANBUS    = $7B;

implementation

end.
